repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types: [file]
        files: ^.*\.(ts|tsx)$
        exclude: ^.*/plasmic/.*$
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@5.62.0"
          - "@typescript-eslint/parser@5.62.0"
          - "eslint@8.44.0"
          - "eslint-config-prettier@8.8.0"
          - "eslint-config-react-app@7.0.1"
          - "eslint-plugin-prettier@4.2.1"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [file]
        files: ^.*\.(js|jsx|ts|tsx|json|css|scss|toml|xml)$
        exclude: ^.*/plasmic/.*$
        additional_dependencies:
          - prettier@2.7.1
